# Generated by Django 4.2.6 on 2023-10-30 06:10

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Brand',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Name', models.CharField(max_length=250)),
                ('created_at', models.DateField()),
                ('updated_at', models.DateField()),
                ('Image', models.ImageField(upload_to='Image/')),
            ],
        ),
    ]
