# Generated by Django 4.2.6 on 2023-10-30 08:25

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('smartphone', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='brand',
            name='created_at',
            field=models.DateTimeField(verbose_name='Created date'),
        ),
        migrations.AlterField(
            model_name='brand',
            name='updated_at',
            field=models.DateTimeField(verbose_name='Updated date'),
        ),
        migrations.CreateModel(
            name='PhoneModels',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('choice_text', models.CharField(max_length=200)),
                ('votes', models.IntegerField(null=True)),
                ('Name', models.CharField(max_length=250)),
                ('Release_year', models.DateField(verbose_name='Realease year')),
                ('Available_quatities', models.IntegerField(null=True)),
                ('price', models.FloatField(null=True)),
                ('created_at', models.DateTimeField(verbose_name='Created date')),
                ('updated_at', models.DateTimeField(verbose_name='Updated date')),
                ('is_available', models.BooleanField(null=True)),
                ('Image', models.ImageField(upload_to='Image/')),
                ('Brand', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='smartphone.brand')),
            ],
        ),
    ]
