# Generated by Django 4.2.6 on 2023-10-30 22:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('smartphone', '0003_remove_phonemodels_choice_text'),
    ]

    operations = [
        migrations.AlterField(
            model_name='brand',
            name='created_at',
            field=models.DateTimeField(auto_now_add=True),
        ),
        migrations.AlterField(
            model_name='brand',
            name='updated_at',
            field=models.DateTimeField(auto_now_add=True),
        ),
    ]
