# Generated by Django 4.2.6 on 2023-10-30 22:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('smartphone', '0004_alter_brand_created_at_alter_brand_updated_at'),
    ]

    operations = [
        migrations.AlterField(
            model_name='brand',
            name='Image',
            field=models.ImageField(upload_to='static/image/'),
        ),
    ]
