# Generated by Django 4.2.6 on 2023-10-30 23:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('smartphone', '0005_alter_brand_image'),
    ]

    operations = [
        migrations.AlterField(
            model_name='brand',
            name='Image',
            field=models.ImageField(upload_to='static/image/brand'),
        ),
    ]
