# Generated by Django 4.2.6 on 2023-10-30 23:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('smartphone', '0006_alter_brand_image'),
    ]

    operations = [
        migrations.AlterField(
            model_name='phonemodels',
            name='Image',
            field=models.ImageField(upload_to='static/image/models'),
        ),
        migrations.AlterField(
            model_name='phonemodels',
            name='Name',
            field=models.CharField(max_length=200),
        ),
        migrations.AlterField(
            model_name='phonemodels',
            name='created_at',
            field=models.DateTimeField(auto_now_add=True),
        ),
        migrations.AlterField(
            model_name='phonemodels',
            name='updated_at',
            field=models.DateTimeField(auto_now_add=True),
        ),
    ]
