# Generated by Django 4.2.6 on 2023-10-31 00:33

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('smartphone', '0008_alter_phonemodels_release_year'),
    ]

    operations = [
        migrations.RenameField(
            model_name='phonemodels',
            old_name='Available_quatities',
            new_name='available_quatities',
        ),
        migrations.RenameField(
            model_name='phonemodels',
            old_name='Brand',
            new_name='brand',
        ),
        migrations.RenameField(
            model_name='phonemodels',
            old_name='Name',
            new_name='name',
        ),
        migrations.RenameField(
            model_name='phonemodels',
            old_name='Release_year',
            new_name='release_year',
        ),
    ]
