# Generated by Django 4.2.6 on 2023-11-07 12:48

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('smartphone', '0009_rename_available_quatities_phonemodels_available_quatities_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='Transactions',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Transaction_type', models.CharField(blank=True, choices=[('card', 'card'), ('cash', 'cash')], max_length=200, null=True)),
                ('Amount', models.IntegerField(null=True)),
                ('Model', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='smartphone.phonemodels')),
                ('User', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
