# Generated by Django 4.2.6 on 2023-11-07 14:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('smartphone', '0010_transactions'),
    ]

    operations = [
        migrations.AlterField(
            model_name='transactions',
            name='Transaction_type',
            field=models.CharField(blank=True, choices=[(1, 'card'), (2, 'cash')], max_length=200, null=True),
        ),
    ]
