# Generated by Django 4.2.6 on 2023-11-07 14:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('smartphone', '0013_rename_is_available_phonemodels_available_number'),
    ]

    operations = [
        migrations.RenameField(
            model_name='phonemodels',
            old_name='available_number',
            new_name='is_available',
        ),
        migrations.AddField(
            model_name='phonemodels',
            name='count',
            field=models.IntegerField(null=True),
        ),
    ]
