# Generated by Django 4.2.6 on 2023-11-07 23:35

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('smartphone', '0014_rename_available_number_phonemodels_is_available_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='phonemodels',
            name='count',
        ),
    ]
