# Generated by Django 4.2.6 on 2023-11-09 14:13

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('smartphone', '0015_remove_phonemodels_count'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='phonemodels',
            name='votes',
        ),
    ]
