# Generated by Django 4.2.6 on 2023-11-15 10:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('smartphone', '0016_remove_phonemodels_votes'),
    ]

    operations = [
        migrations.AddField(
            model_name='phonemodels',
            name='added_quatities',
            field=models.IntegerField(null=True),
        ),
        migrations.AddField(
            model_name='phonemodels',
            name='item_count',
            field=models.IntegerField(null=True),
        ),
        migrations.AddField(
            model_name='phonemodels',
            name='item_sold',
            field=models.IntegerField(null=True),
        ),
    ]
