# Generated by Django 4.2.6 on 2023-11-15 10:44

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('smartphone', '0017_phonemodels_added_quatities_phonemodels_item_count_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='phonemodels',
            name='item_count',
        ),
    ]
