# Generated by Django 4.2.6 on 2023-11-15 11:58

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('smartphone', '0018_remove_phonemodels_item_count'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='phonemodels',
            name='available_quatities',
        ),
    ]
