# Generated by Django 4.2.6 on 2023-11-15 13:04

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('smartphone', '0019_remove_phonemodels_available_quatities'),
    ]

    operations = [
        migrations.RenameField(
            model_name='phonemodels',
            old_name='added_quatities',
            new_name='added_quantities',
        ),
    ]
